#
# this is a template for a module makefile
# Note that at the current delelopment status the user should
# not rely on the order of inclusion of submodules
#
CURRENT := $(call anrem-current-path)

# these are local variables defined with the help of the auto-inclusion system CURRENT path
BUILD_TARGETS_$(CURRENT) := my_target1.o
BUILD_CLEAN_$(CURRENT) := my_clean

# this is autogenerated by anrem-target $(call anrem-target, my_target1.o): path := $(CURRENT)
$(call anrem-target, my_target1.o):
	echo "my_target1.o"
	touch $(path)/my_target1.o

$(call anrem-target, my_clean):
	rm $(path)/*.o

# normal targets can also be defined but the path variable is not set for them
# also they do not benefit of any future improvement in anrem-target
normal_target:
	echo "normal target"
	touch normal_target

# those add to the global anrem build and clean targets the targets defined above
# in future they may be merged into anrem-target directly
$(call anrem-build, $(BUILD_TARGETS_$(CURRENT)))
$(call anrem-clean, $(BUILD_CLEAN_$(CURRENT)))
